.PHONY: clean All

All:
	@echo "----------Building project:[ tempp - Debug ]----------"
	@cd "tempp" && "$(MAKE)" -f  "tempp.mk"
clean:
	@echo "----------Cleaning project:[ tempp - Debug ]----------"
	@cd "tempp" && "$(MAKE)" -f  "tempp.mk" clean
